public class ApexContentClass {
/*
 
# API classes & Their Usecase
-----------------------------

#1 Apex Class: createPlantRestAPI
   Apex Class: plantclassWrapper
   UseCase : REST API to insert multiple records in salesforce by proving list of records as json body

#2 Apex Class: APIForCreatingOppRecord
   Apex Class : OpportunityDetails
   UseCase : Rest API to insert Opportunity record by using json body as Request

3 Apex Class: APItoFindOwnerId
  Apex Class: LeadDetails_client
   UseCase  : Fiding Lead Record and OwnerId by Sending Phone as JSON Body

#4 Apex Class: APIToInsertTask
   Apex Class: TaskCreateAPI
   UseCase   : API For Creating Task Record By using JSON Body

#5 Apex Class: ChatGPT
   LWC Class : ChatGPTSalesforce
   UseCase   : Integration of ChatGPT with Salesforce

#6 Apex Class: CurrencyConvertAPI
   UseCase   : It used to Convert Opportunity Amount into USD before Creating Opportunity record.

#7 Apex Class: PINCodeAPI
   Apex Class: PinCodeResponseWrapper
   UseCase   : It is used it Create Post Office Record based on the Opportunity MaillingPostalCode before creating Opportunity

#8 Apex Class: productUpdateRestAPI
   Apex Class: productUpdateRestAPIWrapper
   UseCase   : It is used to Update Products Data based on the Product code given in the JSON Body;


#9 Apex Class: 
   Apex Class:
   UseCase   : 

#10 Apex Class:
   Apex Class:
   UseCase   : 
































 */ 
}