public class AuraCompContentClass {
    
    /* 

#1 Aura Comp: AccordianComp
Apex Class: AuraCompUtilityClas.getAccounts

UseCase : Here we are using Lightning Accordian, with help we are shwoing Selected Account Details in Accordian Format.

#2 Aura Comp: AccountRelatedContactCheckbox
Apex Class: AuraCompUtilityClas.getAccountontactCheckbox
            AuraCompUtilityClas.getAttachmentId
Quick Action : Show Contact(Account - Object)

UseCase : Clikc on the Button, we will get Related Contact Object, When we clikc on the Preview button, you get Screen where
          we can see that Attachment PDF related to that Contact.


*/
}